-- ────────────────────────────────────────────────────────────
-- Omarchy Custom Theme for Neovim
-- Generated by Omarchist
-- ────────────────────────────────────────────────────────────

return {
	"EdenEast/nightfox.nvim",
	opts = {
		options = {
			transparent = false, -- Define se o fundo será transparente
			terminal_colors = true, -- Habilita cores no terminal
		},
	},
}

